### ISSUE TITLE
Kafka docker restart fail

### ISSUE THREAD

**Issue by agile-lab** [agile-lab-dev/wasp#43]
After a docker-compose restart, zookeeper doesn't reset its state and Kafka launches an exception because an onther broker seems to be already present.

workaround: delete "data" folder of zookeeper docker before restart.

**Comment by nicolobidotti** [comment]
This manifests itself with the error "A broker is already registered on the path /brokers/ids/*id*. This probably indicates that you either have configured a brokerid that is already in use, or else you have shutdown this broker and restarted it faster than the zookeeper timeout so it appears to be re-registering." in the Kafka container logs.

This is due to the default zookeeper session timeout used by Kafka, 6000ms, and the fact that Kafka uses ephemeral nodes for broker registration. Ephemeral nodes last as long as the session that generated them.

If the time it takes to stop & restart the Kafka container is not at least that much, it resumes the previous zookeeper session, which means the previous node doesn't get deleted, which causes the error.

Note: even if the timout is in ms, it's misleading: when a ZooKeeper ensemble goes down, time freezes, so the session does not expire unless zookeeper is up and running!

To fix it it should be enough to set the session timeout to 1000ms or so.

Another, less drastic workaround that can be used, is to let the services run for a couple seconds after the Kafka container exits, then stop and restart them all. This ensures the session times out and the  broker registration nodes get deleted.

**Comment by agile-lab** [comment]
I think we can try with the first solution in order to understand if the diagnosis is correct

**Comment by dbtucker** [comment]
A more deterministic option (in the case where the hostname of the Kafka broker remains constant) is enhance the broker start-up routine to hold-off launching the service until the hostname is NO LONGER in the /brokers list reported by zookeeper.
